# Generated by Django 5.1.2 on 2024-11-01 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="FinancialDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_year", models.IntegerField()),
                ("revenue", models.BigIntegerField()),
                ("net_income", models.BigIntegerField()),
                ("total_assets", models.BigIntegerField()),
                ("total_liabilities", models.BigIntegerField()),
                ("operating_cash_flow", models.BigIntegerField()),
                ("capital_expenditures", models.BigIntegerField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis.company",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "report_year")},
            },
        ),
        migrations.CreateModel(
            name="FinancialIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_year", models.IntegerField()),
                ("gross_profit_margin", models.FloatField()),
                ("net_profit_margin", models.FloatField()),
                ("debt_ratio", models.FloatField()),
                ("free_cash_flow", models.BigIntegerField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis.company",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "report_year")},
            },
        ),
    ]
