# Generated by Django 5.1.2 on 2024-11-18 07:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="FinancialDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("revenue", models.BigIntegerField(blank=True, null=True)),
                ("net_income", models.BigIntegerField(blank=True, null=True)),
                ("operating_expenses", models.BigIntegerField(blank=True, null=True)),
                ("r_and_d_costs", models.BigIntegerField(blank=True, null=True)),
                ("shares_outstanding", models.BigIntegerField(blank=True, null=True)),
                ("cogs", models.BigIntegerField(blank=True, null=True)),
                ("gross_profit", models.BigIntegerField(blank=True, null=True)),
                ("total_assets", models.BigIntegerField(blank=True, null=True)),
                ("current_assets", models.BigIntegerField(blank=True, null=True)),
                ("current_liabilities", models.BigIntegerField(blank=True, null=True)),
                (
                    "cash_and_cash_equivalents",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("total_liabilities", models.BigIntegerField(blank=True, null=True)),
                ("shareholders_equity", models.BigIntegerField(blank=True, null=True)),
                ("operating_cash_flow", models.BigIntegerField(blank=True, null=True)),
                ("capital_expenditures", models.BigIntegerField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis.company",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "year")},
            },
        ),
        migrations.CreateModel(
            name="FinancialIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "gross_profit_margin",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "operating_profit_margin",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "net_profit_margin",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "profit_growth_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "earnings_per_share",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "debt_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "current_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "cash_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "operating_cash_flow",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "free_cash_flow",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "capital_expenditure_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis.company",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis.financialdocument",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "year")},
            },
        ),
    ]
