# Generated by Django 5.1.3 on 2024-11-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialdocument",
            name="capital_expenditures",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="financialdocument",
            name="net_income",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="financialdocument",
            name="operating_cash_flow",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="financialdocument",
            name="revenue",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="financialdocument",
            name="total_assets",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="financialdocument",
            name="total_liabilities",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
