# Generated by Django 5.1.2 on 2024-11-11 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0002_alter_financialdocument_capital_expenditures_and_more 2"),
        ("analysis", "0002_alter_financialdocument_capital_expenditures_and_more"),
    ]

    operations = []
