# Generated by Django 5.1.2 on 2024-11-11 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0002_financialdocument_cogs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialindicator",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analysis.financialdocument",
            ),
        ),
    ]
