# Generated by Django 5.1.2 on 2024-11-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0003_alter_financialindicator_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialdocument",
            name="gross_profit",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
