# Generated by Django 5.1.2 on 2024-11-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0004_financialdocument_gross_profit"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialdocument",
            name="operating_expenses",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financialdocument",
            name="r_and_d_costs",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financialdocument",
            name="shares_outstanding",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
