# Generated by Django 5.1.2 on 2024-11-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0005_financialdocument_operating_expenses_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialdocument",
            name="cash_and_cash_equivalents",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financialdocument",
            name="current_assets",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financialdocument",
            name="current_liabilities",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financialdocument",
            name="shareholders_equity",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
